package com.sjw.beautifulapp.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.sjw.beautifulapp.bean.LoveFileBean;

import com.sjw.beautifulapp.greendao.LoveFileBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig loveFileBeanDaoConfig;

    private final LoveFileBeanDao loveFileBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        loveFileBeanDaoConfig = daoConfigMap.get(LoveFileBeanDao.class).clone();
        loveFileBeanDaoConfig.initIdentityScope(type);

        loveFileBeanDao = new LoveFileBeanDao(loveFileBeanDaoConfig, this);

        registerDao(LoveFileBean.class, loveFileBeanDao);
    }
    
    public void clear() {
        loveFileBeanDaoConfig.clearIdentityScope();
    }

    public LoveFileBeanDao getLoveFileBeanDao() {
        return loveFileBeanDao;
    }

}
